import React, { useState } from 'react';
import { AlertTriangle, CheckCircle, FileText, ArrowLeft, Loader2, ShieldAlert } from 'lucide-react'; // Added ShieldAlert here
import { Link, useParams } from 'react-router-dom';

const ContractScanner = () => {
  const [text, setText] = useState("");
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const { patronId } = useParams();

  const handleAnalyze = async () => {
    if(!text) return;
    setLoading(true);
    setAnalysis(null);

    try {
      const res = await fetch('/api/agent/review-contract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contract_text: text })
      });
      
      const data = await res.json();
      setAnalysis(data);
    } catch (error) {
      console.error("Agent failed", error);
      alert("Something went wrong connecting to the AI agent.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col font-sans">
      
      {/* Navbar Area */}
      <div className="bg-white border-b px-6 py-4 flex items-center gap-4">
        <Link to={`/${patronId}/ai`} className="text-gray-500 hover:text-black transition">
            <ArrowLeft size={20} />
        </Link>
        <h1 className="text-xl font-serif font-bold">AI Contract Auditor</h1>
      </div>

      <div className="flex-1 flex flex-col md:flex-row max-w-7xl mx-auto w-full p-6 gap-6">
        
        {/* LEFT: Input Area */}
        <div className="w-full md:w-1/2 flex flex-col bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          <div className="p-4 border-b bg-gray-50">
            <label className="text-sm font-bold text-gray-700 flex items-center gap-2">
                <FileText size={16} /> Paste Agreement Text
            </label>
          </div>
          <textarea 
            className="flex-1 p-6 resize-none focus:outline-none focus:bg-purple-50/30 transition text-gray-800 leading-relaxed text-sm"
            placeholder="Paste the full text of the Consignment or Sale agreement here..."
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <div className="p-4 border-t bg-gray-50">
            <button 
              onClick={handleAnalyze}
              disabled={loading || !text}
              className={`w-full py-3 rounded-lg font-bold text-white transition-all flex items-center justify-center gap-2
                ${loading || !text ? 'bg-gray-400 cursor-not-allowed' : 'bg-black hover:bg-gray-800 hover:shadow-lg'}
              `}
            >
              {loading ? <><Loader2 className="animate-spin" /> Analyzing Legal Risks...</> : "Run Legal Audit"}
            </button>
          </div>
        </div>

        {/* RIGHT: Agent Output Area */}
        <div className="w-full md:w-1/2 bg-white rounded-xl shadow-sm border border-gray-200 overflow-y-auto max-h-[85vh]">
          
          {!analysis && !loading && (
            <div className="h-full flex flex-col items-center justify-center text-gray-400 p-10 text-center">
              <ShieldAlert size={48} className="mb-4 text-gray-200" />
              <p>Results will appear here after analysis.</p>
            </div>
          )}

          {loading && (
            <div className="h-full flex flex-col items-center justify-center p-10 space-y-4">
              <Loader2 className="w-10 h-10 text-purple-600 animate-spin" />
              <p className="text-gray-500 animate-pulse">Reading clauses...</p>
              <p className="text-gray-500 animate-pulse delay-75">Checking against Art Law database...</p>
            </div>
          )}

          {analysis && (
            <div className="p-8 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
              
              {/* Header Score */}
              <div className="flex items-center justify-between border-b pb-6">
                <div>
                    <h2 className="text-2xl font-serif font-bold">Audit Report</h2>
                    <p className="text-gray-500 text-sm">Generated by AI Agent</p>
                </div>
                <div className={`text-center px-4 py-2 rounded-lg border-2 
                    ${analysis.risk_score > 50 ? 'border-red-100 bg-red-50 text-red-700' : 'border-green-100 bg-green-50 text-green-700'}`}>
                    <span className="block text-xs font-bold uppercase tracking-wider">Risk Score</span>
                    <span className="text-3xl font-black">{analysis.risk_score}/100</span>
                </div>
              </div>

              {/* Summary */}
              <div className="bg-blue-50 p-4 rounded-lg border border-blue-100 text-blue-900 leading-relaxed text-sm">
                <span className="font-bold block mb-1"> Executive Summary:</span>
                {analysis.summary}
              </div>

              {/* Dangerous Clauses */}
              <div>
                <h3 className="text-red-600 font-bold flex items-center gap-2 mb-3">
                    <AlertTriangle size={18} /> Dangerous Clauses Found
                </h3>
                {analysis.dangerous_clauses.length > 0 ? (
                    <ul className="space-y-3">
                        {analysis.dangerous_clauses.map((item, i) => (
                            <li key={i} className="bg-red-50 border-l-4 border-red-500 p-3 text-sm text-gray-700 rounded-r-md">
                                {item}
                            </li>
                        ))}
                    </ul>
                ) : (
                    <p className="text-gray-500 italic text-sm">No critical threats detected.</p>
                )}
              </div>

              {/* Missing Clauses */}
              <div>
                <h3 className="text-orange-600 font-bold flex items-center gap-2 mb-3">
                    <AlertTriangle size={18} /> Critical Missing Protections
                </h3>
                <ul className="space-y-2">
                    {analysis.missing_clauses.map((item, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
                            <span className="text-orange-400 mt-1">•</span> {item}
                        </li>
                    ))}
                </ul>
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ContractScanner;